name: alpha_twelve_interview
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: IBMPlexSans
      fonts:
        # - asset: assets/fonts/IBMPlexSans-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
        #   weight: 100
        #   style: italic
        # - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: assets/fonts/IBMPlexSans-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
        #   weight: 300
        #   style: italic
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        # - asset: assets/fonts/IBMPlexSans-Italic.ttf
        #   weight: 400
        #   style: italic
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        # - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
        #   weight: 600
        #   style: italic
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        # - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
        #   weight: 700
        #   style: italic
        # - asset: assets/fonts/IBMPlexSans-ExtraBold.ttf
        #   weight: 800
        # - asset: assets/fonts/IBMPlexSans-ExtraBoldItalic.ttf
        #   weight: 800
        #   style: italic
